sudo: required
services:
  - docker

before_install:
  - docker build -t ryandussiaume/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ryandussiaume/react-test npm test -- --coverage

after_success:
  - docker build -t ryandussiaume/multi-client ./client
  - docker build -t ryandussiaume/multi-nginx ./nginx
  - docker build -t ryandussiaume/multi-server ./server
  - docker build -t ryandussiaume/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push ryandussiaume/multi-client 
  - docker push ryandussiaume/multi-nginx
  - docker push ryandussiaume/multi-server
  - docker push ryandussiaume/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-955874340143
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY